name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Your Issue has been received, we shall get back to you with a solution."
        pr-message: "Hello, thanks for creating a pull request to our repo, we shall act accordingly."
